### ISSUE TITLE
Unable to install release 1.0 via Cocoapods

### ISSUE THREAD

**Issue by EndEGroup** [rebeloper/SwiftyPlistManager#1]
Hello,

Currently having issues trying to install via Cocoapods.  'pod install' returns the following error: [!] Unable to find a specification for 'SwiftyPlistManager'

**Comment by rebeloper** [comment]
Try
`pod 'SwiftyPlistManager', :git => 'https://github.com/rebeloper/SwiftyPlistManager.git', :tag => '1.0.1'`
