### ISSUE TITLE
Development target iOS 8 unable to install via cocoa pods 

### ISSUE THREAD

**Issue by rpzzzzzz** [rebeloper/SwiftyPlistManager#2]
Specs satisfying the `SwiftyPlistManager` dependency were found, but they required a higher minimum deployment target.

Can you decrease your development target to iOS 8

**Comment by Notsileous** [comment]
You are seriously limiting your potential audience by restricting it to such a high deployment target.

**Comment by rebeloper** [comment]
Thanks for the suggestion. Just decreased to iOS8
