### ISSUE TITLE
Plist of type Array instead of Dictionary?

### ISSUE THREAD

**Issue by seenoevo** [rebeloper/SwiftyPlistManager#4]
First of all, great tutorial! 

In fact, one of the best and detailed tutorials in helping us get started with using plist files!

I'm trying to use this in my own app, but the problem I have is that my plist files are of type `Array`, not `Dictionary`.

![untitled](https://user-images.githubusercontent.com/8109158/31871261-cf875d5c-b767-11e7-90a3-6ace8fb370b7.png)

How would I be able to add a value to the array using `SwiftyPlistManager.shared.addNew(dic, key: firstKey, toPlistWithName: dataPlistName)` if there is no associated key?

**Comment by rebeloper** [comment]
You need to add the array to the dict first and than finally as the last step ad the dict yo the plist file. To retrieve any element of the array you will first have to retrieve the dict from the plist and than get the array and the desired element from the dict.

**Comment by Karthigak** [comment]
Would be better adding sample for this?
