### ISSUE TITLE
Cannot Fetch Root Element

### ISSUE THREAD

**Issue by LoicVerrall** [rebeloper/SwiftyPlistManager#5]
Hi, thanks for developing this - I love it.

Just a quick question, I'm using the following line:

`let allAnimals = SwiftyPlistManager.shared.fetchValue(for: "Root", fromPlistWithName: "WildlifeData")`

 to fetch the entire dictionary of elements, but I am getting the following error message:

> WARNING: The Value for key 'Root' does not exist in WildlifeData.plist! Please, check your spelling.

FYI, my `plist` looks like this:
<img width="451" alt="screen shot 2017-10-23 at 10 29 10" src="https://user-images.githubusercontent.com/17081120/31881918-07faf228-b7dd-11e7-9206-61f2f25bcc4a.png">

**Comment by rebeloper** [comment]
Hi, you cannot fetch root. It is already "fetched". Instead fetch one of the elements (ex. Bengal Tiger). There is a step by step tutorial on my site: https://rebeloper.com/read-write-plist-file-swift/

**Comment by LoicVerrall** [comment]
Yes, but I was wondering whether there was a way to fetch all the elements, rather than just one at a time?

**Comment by rebeloper** [comment]
Sure, just add a dictionary to root and than add all your elements to that dictionary. Now you can fetch that dictionary and grab the elements later.

**Comment by LoicVerrall** [comment]
Perfect, thanks!
